#pragma kernel CSMain

RWTexture2D<float4> Result;
float Width;
float Height;
bool Overlay;
bool Invert;

[numthreads(8,8,1)]
void CSMain(uint3 id : SV_DispatchThreadID) {
	float value = id.x / Width;
	if (Invert) {
		value = 1.0 - value;
	}
	const float4 color = float4(value, value, value, 1.0);
	
	if (Overlay) {
		Result[id.xy] = Result[id.xy] * color;
	} else {
		Result[id.xy] = float4(value, value, value, 1.0);
	}
}
